### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by IRONMAN8599** [foxzsz/discord-vanity-sniper-GO#1]
![Screenshot_2022_0527_165908](https://user-images.githubusercontent.com/93428017/170691092-be57f9f4-795f-4071-8556-90642b6c3834.png)
help

**Comment by foxzsz** [comment]
Hello, please do ```go run . ``` to run the code and not anything else, or it will provide that error. Also make sure you have Go version 1.18

**Comment by IRONMAN8599** [comment]
thx

**Comment by IRONMAN8599** [comment]
I do not expect this much fast support

**Comment by IRONMAN8599** [comment]
![Uploading Screenshot_2022_0527_172511.png…]()

**Comment by IRONMAN8599** [comment]
helpp

**Comment by foxzsz** [comment]
Can you stop spamming the open and close button?

**Comment by foxzsz** [comment]
You need to get better proxies if it's not displaying any checks at all.

**Comment by IRONMAN8599** [comment]
ok and sry
